#!/usr/bin/sh

# x86-64 instructions: https://www.felixcloutier.com/x86/
# more reading: https://wiki.osdev.org/X86-64_Instruction_Encoding
#             - https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html
#             /r                -> reg and r/m operand
#             ib, iw, id, io    -> immediate value byte size 1, 2, 4, 8
#             +rb, +rw, +rd +ro -> lower 3 opcode bits encode register

FILE="hx"
INST="$(date +%s)"
BUFF=$FILE
SIZE=0

if test -e "$FILE" ; then
    rm "$FILE"
fi

WriteZeroes () {
    for i in $(seq 1 "$1") ; do
        SIZE=$(expr $SIZE + 1)
        printf '\x00' >> $BUFF
    done
}

WriteBits8 () {
    SIZE=$(expr $SIZE + 1)
    printf "\\$(printf '%o' "$((2#$1))")" >> $BUFF
}

WriteU8  () {
    SIZE=$(expr $SIZE + 1)
    printf "\x$1" >> "$BUFF"
}

WriteU16 () {
    WriteU8 $2
    WriteU8 $1
}

WriteU32 () {
    WriteU16 $3 $4
    WriteU16 $1 $2
}

WriteU64 () {
    WriteU32 $5 $6 $7 $8
    WriteU32 $1 $2 $3 $4
}

Write_ph () {
    # PROGRAM header
    ####################
    WriteU32 00 00 00 01                # p_type        | program type load 
    WriteU32 00 00 00 07                # p_flags       | program flags set to read, write and executable
    WriteU64 00 00 00 00 00 00 00 00    # p_offset      | when does the segment start -> elf + program header
    WriteU64 00 00 00 00 00 40 00 00    # p_vaddr       | virtual base address
    WriteZeroes 8                       # p_paddr       | ignored on my system

    hex=$(printf '%016x' $1)
    # p_filesz      | accumulated bytes of the instructions
    WriteU64 "${hex:0:2}" "${hex:2:2}" "${hex:4:2}" "${hex:6:2}" "${hex:8:2}" "${hex:10:2}" "${hex:12:2}" "${hex:14:2}"
    # p_memsz       | do not allocate more memory in the image than instructions
    WriteU64 "${hex:0:2}" "${hex:2:2}" "${hex:4:2}" "${hex:6:2}" "${hex:8:2}" "${hex:10:2}" "${hex:12:2}" "${hex:14:2}"

    WriteU64 00 00 00 00 00 00 00 00    # p_align       | has something to do with v_addr and p_offset 
}

# ELF header
###############
WriteU32 46 4c 45 7f                # elf identifier
WriteU8 02                          # class         | 64 bit
WriteU8 01                          # data encoding | lsb
WriteU8 01                          # file version  | 1 current
WriteU8 03                          # operating system/ABI identification
WriteU8 00                          # ABI version   | 0 - no features
WriteZeroes 7                       # padding

WriteU16 00 02                      # e_type        | exe
WriteU16 00 3e                      # e_machine     | AMD
WriteU32 00 00 00 01                # e_version     | current
WriteU64 00 00 00 00 00 40 00 78    # e_entry       | set virtual base address
WriteU64 00 00 00 00 00 00 00 40    # e_ph_off      | program header immediatle after the elf header
WriteZeroes 8                       # e_shoff       | no section headers
WriteZeroes 4                       # e_flags       | no flags
WriteU16 00 40                      # e_h_size      | elf header size
WriteU16 00 38                      # e_ph_ent_size | size of program headers
WriteU16 00 01                      # e_ph_num      | number of program headers 
WriteZeroes 2                       # e_shentsize   | not used.
WriteZeroes 2                       # e_shnum       | not used.
WriteZeroes 2                       # e_shstrndx    | not used.

SIZE=0
BUFF=$INST

WriteBits8  10111111                # mov r32, imm32
WriteU32    00 00 00 11
WriteBits8  10111111                # mov r32, imm32
WriteU32    00 00 00 01
WriteBits8  10111000                # mov r32, imm32
WriteU32    00 00 00 3c
WriteU16    05 0f

BUFF=$FILE
Write_ph $SIZE
cat $INST >> $FILE

ndisasm -ab64 $INST

chmod +x $FILE
./$FILE

rm $INST

